### ISSUE TITLE
avr128da32 cannot be flashed the second time

### ISSUE THREAD

**Issue by wimalopaan** [microchip-pic-avr-tools/pymcuprog#17]
I flashed a simpled pin-toggler successful. Then I want to overwrite this with another content.
pymcuprog states success, but the flash isn't overwritten, I have to explicitly erase and then write. Then the new content is flashed successfully.

**Comment by mraardvark** [comment]
See: https://github.com/microchip-pic-avr-tools/pymcuprog/issues/8
The --erase switch is not yet in production release, but available on https://test.pypi.org/project/pymcuprog/

**Comment by wimalopaan** [comment]
Ok, thanks
