### ISSUE TITLE
pymcuprog cannot write to attiny414

### ISSUE THREAD

**Issue by dgtie** [microchip-pic-avr-tools/pymcuprog#24]
pymcuprog can ping and seems can read(verify) from attiny414. But it fails to upload code to attiny414. There is no problem when switch back to pyupdi.

**Comment by dgtie** [comment]
I got it to work with pymcuprog. I have to erase before writing.

**Comment by xedbg** [comment]
Yupp - common misunderstanding, I'm afraid.
(There is an update which supports --erase, but I think its stuck in pre-release on pypi test)
