### ISSUE TITLE
AVR32DB48 device info missing

### ISSUE THREAD

**Issue by grandaspanna** [microchip-pic-avr-tools/pymcuprog#3]
Along with a couple of others. I manually created one for my project, but someone pointed out that it should be captured here.

**Comment by xedbg** [comment]
Logged internally: DSG-3633

**Comment by xedbg** [comment]
Missing DBs, EAs, DDs are now in 3.10.2
https://github.com/microchip-pic-avr-tools/pymcuprog/tree/main/pymcuprog/deviceinfo/devices
