### ISSUE TITLE
attiny424 is not supported

### ISSUE THREAD

**Issue by mraardvark** [microchip-pic-avr-tools/pymcuprog#4]

**Comment by xedbg** [comment]
Logged internally: DSG-3635

**Comment by xedbg** [comment]
Added missing devices. Beta release on test.pypi:
pip install -i https://test.pypi.org/simple/ pymcuprog==3.9.4.126

**Comment by SpenceKonde** [comment]
These are still missing from the github repo... I wound up synthesizing them from other device definitions for megaTinyCore 2.4.0.

**Comment by xedbg** [comment]
Sorry about that - I will look at adjusting the QA process to make releasing to github more frequent - right now it it only downstream from the pypi production release (not test.pypi) which has some added testing requirements.

**Comment by SpenceKonde** [comment]
Aaaha, yeah - I would think the natural thing to do would be for the github repo to be updated with the latest code; Github has a "release" feature that is designed for declaring a snapshot of the repo to be production grade.

**Comment by xedbg** [comment]
tiny424 and friends are now in 3.10.2
https://github.com/microchip-pic-avr-tools/pymcuprog/tree/main/pymcuprog/deviceinfo/devices
