### ISSUE TITLE
No CLI Documentation

### ISSUE THREAD

**Issue by WestfW** [microchip-pic-avr-tools/pymcuprog#7]
There doesn't seem to be any documentation for using pymcuprog via the CLI, other than that provided by the "pymcuprog --help" command.  How about creating such a file, even if it no more than a copied output of the help command?

Having to browse the source or install and run the program just to see what commands are available is sub-optimal!

**Comment by xedbg** [comment]
added help.md in 3.10.2
https://github.com/microchip-pic-avr-tools/pymcuprog/blob/main/help.md
this will probably grow and be tweaked over time.
Thanks for the input!

**Comment by T3sl4co1l** [comment]
Thanks, that's much clearer!

- Regarding hex, would it be worth mentioning what offsets correspond to which memory types?  (If this is inconsistent across families, perhaps a note of "refer to family [tools/guides]" would suffice?)
- What -t options are supported?  (How do I know if I can use what I have, and how exactly is it named?)
- How do options interact, e.g. is -b only used for read? If for write, then I assume it could be used to truncate a file?
- CLK is also baud

**Comment by xedbg** [comment]
Also good points, thanks - logged a new one: DSG-3972 
(Your initial input was well-timed during release week, and sufficiently cosmetic to sneak in.  But documentation is continuously improved)

- hex offsets are interesting in that PIC and SAM use "actual" offsets, while AVRs traditionally use a fabricated offset - I am not sure where these are documented as its the linker's job ("not our problem" :/ ) but a good idea to put in.  
- tool options are easy to add, yes.  these come from pyedbglib, but still worth adding here (including aliases which i forget we even have)

Any further suggestions, please post them here!

**Comment by WestfW** [comment]
I think the fuse issue is somewhat the fault of avr-gcc/avr-libc.  If you include the fuses in the source code (via the FUSES macro), they want ALL the fuses and create a single linker section that contains values for all of the fuses.  That made sense with the older AVRs where all the options got scatter/gathered into two or three bytes of fuses, but it's less convenient with the UDPI AVRs where there are more fuses, many of which make sense to set individually.)
(for example, I'd really like optiboot_x source to be able to specify "set the BOOTEND fuse to 2, but don't bother touching any of the other fuses.  And AFAIK, I can't.)

**Comment by T3sl4co1l** [comment]
Yeah, not really any good way to specify that; you'll have to RMW them manually, I suppose. (What's a good way to script that, anyway?  Can the -- hey wait, does the program return ERRORLEVEL from a single byte read?  Okay, probably dumb, because plenty of reasons, but just saying, that'd be cute...)  Otherwise, would need a specific AND/OR/XOR mode.

Whereas, the compile-time values, make sense from a production standpoint: you want *this* configuration, and that's that.
