### ISSUE TITLE
Feature request: perform erase before flashing

### ISSUE THREAD

**Issue by T3sl4co1l** [microchip-pic-avr-tools/pymcuprog#8]
Hello,

This tool happily corrupts device data.  Namely, a Flash write cycle is just that, write only.  I understand this from a point of expressiveness, and that's fine for library purposes.  For practical purposes, you're always erasing beforehand.  When using from CLI, I have to manually run an erase cycle first, or put two commands into a batch/script, to actually reprogram a device.

Erase should simply be another option.

Inconsistency: it seems fuses NEVER need to be erased.  (I don't know offhand if that's a quirk of UPDI or what.)

**Comment by xedbg** [comment]
This didn't make the cut for 3.10.2 and will be scoped for 'next' release

**Comment by xedbg** [comment]
@T3sl4co1l :
Version 3.11 on pypi test has --erase switch on write: https://test.pypi.org/project/pymcuprog/3.11.3.142/

as documented, and as suggested here, this  is the "lowest-cost" solution in terms of simplicity and back-compatibility.
--erase will do a chip erase before writing from an **Intel hex file**
It will **not** work for writing bin or literal (excluded to avoid complications)

**Comment by xedbg** [comment]
Hi Dominic, It has unfortunately been slipping out of the last few sprints, but we still hope to release it this side of summer.  Which means May/June.  
(There should be few risks attached, but we need to run a set of QA procedures.)
Its good that you ping us like this - then we are aware of you!
